# Generated by Django 4.2.2 on 2023-06-19 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crackerjacksapi', '0004_alter_parkrating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='attendees',
            field=models.ManyToManyField(related_name='attending', to='crackerjacksapi.crackerjacksuser'),
        ),
    ]
